import Header from "@/components/Header";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Footer from "@/components/Footer";
import getCurrentUser from "@/actions/getCurrentUser";
import { SafeUser } from "@/types";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: "--font-inter",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser: SafeUser | null = await getCurrentUser();

  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Header currentUser={currentUser} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
